### ISSUE TITLE
ILT0038 compilation error on UWP with .NET Native

### ISSUE THREAD

**Issue by kevcrooks** [sveinungf/spreadcheetah#58]
After updating the packager from 1.14.0 to 1.15.0, I'm unable to compile for UWP in release mode (using .NET Native).

I get the following error:

`ILT0038: 'SpreadCheetah.CellValues.CellValue' is a value type with a default constructor. Value types with default constructors are not currently supported. Consider using an explicit initialization function instead.`

I haven't found a workaround yet to be able to use this package. Is this something that can be fixed, or is there a workaround to get the build running?

**Comment by sveinungf** [comment]
Thanks for the feedback. I'm not that familiar with UWP and I don't know of any workarounds you can use for version 1.15.0. It seems to be the same issue as is being discussed here: https://github.com/dotnet/roslyn/issues/67187.

If there are no good workarounds then I can look into a fix. I will be out travelling for the next weeks, so any new version will have to wait until I'm back. Perhaps the best course of action would be to stay on version 1.14.0 in the meantime.

**Comment by sveinungf** [comment]
This has been fixed in version 1.16.0.
